config/routes.rb
Rails.application.routes.draw do
  get '/404', :to => 'application#page_not_found'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations",omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'auth/google_oauth2/callback', to: 'users/sessions#create'
  end
  get '/users/:id/edit', to: "users/registrations/#edit"
  resources :categories
  get '/my_projects', to: "my_projects#view_all", as:"my_projects"
  get '/fund_request', to: "my_projects#fund_request", as:"fund_request"
  get '/my_wishlist', to: "my_projects#my_wishlist", as:"my_wishlist"
  get '/my_foundings', to: "my_projects#my_foundings", as:"my_foundings"
  post '/create_promise', to: "my_projects#create_promise"
  post '/delete_promise', to: "my_projects#delete_promise"
  post '/create_item', to: "my_projects#create_item"

  get '/admin', to: "admin#index", as:"admin"
  resources :projects
  get '/', to: "home#index", as:'home'
  get 'login', to: "session#login"
  post 'login', to: "session#create"
  get '/profile/:id', to: "profile#show", as: "user_profile"
  get '/edit_profile/:id', to: "profile#edit"
  patch '/edit_profile', to: "profile#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/payment/promises/:id', to: "payments#promises", as: "pay_promise"
  post '/payment/pay', to: "payments#pay"

  get '/payments/fund/:id', to: "payments#fund"

  get '/admin/get_users', to: "admin#get_users", as: 'admin_get_users'
  get '/admin', to: "admin#index"

  post '/wishlist/project/', to: "my_projects#add_to_wishlist"
  delete '/wishlist/project/', to: "my_projects#remove_from_wishlist"
  post '/projects/status/:id', to: "projects#status"
  get '/projects/categories/search', to: "categories#search_by_category"

  post '/fund_request/reject/:id', to: "my_projects#reject_fund"
  post '/fund_request/accept/:id', to: "my_projects#accept_fund"


end

app/controllers/my_projects_controller.rb
class MyProjectsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: :add_to_wishlist

  def index

  end


  def view_all
    @user=User.find_by(id:current_user.id)
  end

  def split_email(email)
    return email.split('@')[0]
  end

  def fund_request
    user_id = current_user
    if user_id.nil?
      user = User.find_by(token: params[:token])
      user_id = User.find_by(token: params[:token]).id
      sing_in(:user, user)
    else
      user_id = current_user.id
    end
    @funds = Founding.where(state: "waiting")
    @my_request = []
    @funds.each do |f|
      if f.project.user_id == current_user.id
        @my_request.push(f)
      end
    end
  end

  def my_wishlist
    @user = User.find(current_user.id)
  end

  def my_foundings
    @user=User.find(current_user.id)

    @my_foundings_rows=Founding.where(user_id:@user.id)
  end

  def remove_from_wishlist
    wishlist_project = WishlistProject.where(project_id:params[:project], wishlist_id:params[:wishlist]).first
    wishlist_project.destroy
    flash[:wishlist] = "Project was removed from your wishlist"
    redirect_to '/my_wishlist'
  end
  def accept_fund
    @fund = Founding.find(params[:id])
    @fund.update(state: "accepted")
    flash[:accepted_fund] = "You have accepted the fund request!"
    redirect_to '/fund_request'
  end
  def reject_fund
    @fund = Founding.find(params[:id])
    @fund.update(state: "rejected")
    flash[:rejected_fund] = "You have rejected the fund request!"
    redirect_to '/fund_request'
  end

  def add_to_wishlist

    @user = User.find (current_user.id)

    if @user.nil?
      flash_notice="You must sign in"
      value = {:"success" => "exist",flash:flash_notice}
      puts flash
      render :json => value

    end
    wishlist = @user.wishlist

    if wishlist.nil?
      Wishlist.create(user_id: @user.id)
      wishlist = @user.wishlist
      puts wishlist.nil?
    end


    project_id=params[:id]

    the_project=Project.find_by(id:project_id,user_id:@user.id)

    puts the_project
    if !the_project.nil?
      flash_notice="You cannot add your project to wishlist"
      value = {:"success" => "exist",flash:flash_notice}
      render :json => value
      return false
    end

    exist = WishlistProject.find_by(wishlist_id:wishlist.id, project_id: project_id)

    if !exist.nil?
      flash_notice="The project already exists in your wishlist"
      value = {:"success" => "exist",flash:flash_notice}

      render :json => value
      return false
    end

    flash_notice="Project added to wishlist"
    add = WishlistProject.create(wishlist_id: @user.wishlist.id, project_id: params[:id])
    value = {:"success" => true,flash:flash_notice}
    render :json => value
  end
  def create_promise
    quantity = params[:quantity]
    description = params[:description]
    image = params[:image]
    project = Project.find(params[:project_id])
    price = params[:price]
    Promise.create(project_id:project.id, price:price, quantity:quantity, description:description)
    flash[:created_promise] = "The promise was created!"
    redirect_to '/projects/' + params[:project_id].to_s + '/edit'
  end
  def delete_promise
    promise = Promise.find(params[:id])
    promise.destroy()
    flash[:deleted_promise] = "The promise was deleted!"
    redirect_to '/projects/' + params[:project_id].to_s + '/edit'

  end

  def create_item
    promise = params[:promise_id]
    image = params[:image]
    name = params[:name]
    item = Item.create(promise_id:promise, name:name)
    multimedia = MultimediaContent.create(item_id:item.id, name:name ,image:image)
    flash[:item_created] = "The item was created!"
    redirect_to '/projects/' + params[:project_id].to_s + '/edit'
  end


end

app/helpers/my_projects_helper.rb
module MyProjectsHelper
end

app/views/my_projects/_aside_menu.html.erb
<style>
  .left{

    margin-left: 40px;
    width: 100%;

  }

    .left>.list-group>a{
      color: white;
      background-color: rgba(0, 0, 0, 0.5)
    }
  .left>.list-group>a.selected{
    color: white;
    background-color: rgba(0, 45, 94, 0.71)
  }


</style>


<div class="row">
  
  <div class="left animated fadeIn">
  <div class="list-group col-sm-2 ">
    <a href="<%= my_projects_url %>" class="list-group-item <%="selected" if selected_item==0 %>">
      <p class="list-group-item-text">My Projects</p>
    </a>
    <a href="<%= my_wishlist_url %>" class="list-group-item <%="selected" if selected_item==1 %>">
      <p class="list-group-item-text">My Wislist</p>
    </a>
    <a href="<%= my_foundings_url %>" class="list-group-item <%="selected" if selected_item==2 %>">
      <p class="list-group-item-text">Founded by me</p>
    </a>
    <a href="<%= fund_request_url %>" class="list-group-item <%="selected" if selected_item==3 %>">
      <p class="list-group-item-text">Found Request</p>
    </a>

  </div>
  </div>
  <%= yield %>

  <button id="add_project_button" href style="padding:auto;position:fixed;bottom:10%;right: 7%;display:block;
      height: 70px;
      width: 70px;
      border-radius: 50%;
      border: 1px black;
      text-decoration-color: aliceblue;
      background-color: rgb(0,88,158);
  ">
    <%= link_to new_project_url()do%>
      <i style="color: rgb(219,219,219)" class="glyphicon glyphicon-plus"></i>
      <label  style="color: #dbdbdb">Add Project</label>
    <% end %>
  </button>


</div>
<script>
$("#add_project_button").hover(function () {
    $("#add_project_button").animateCss("bounce", function () {
        $("#add_project_button").attr("class", "");
    });;

});
</script>

app/views/my_projects/fund_request.html.erb
<%= render 'aside_menu', :selected_item=>3 do %>
  <div class="col-sm-8" style="padding:0 0 0 0 ">

    <div class="project_show_Table animated fadeIn">
      <div style="color: green"><%= flash[:accepted_fund] %></div>
      <div style="color: red"><%= flash[:rejected_fund] %></div>
      <h1 style="color: white;text-align: center;"> Fund Request by <%= current_user.email %></h1>

      <table class="table">
        <tr><th>Project Title</th>
          <th>User</th>

          <th>Amount</th>

          <th colspan="2">Actions</th>

        </tr>
        <%
          if not @my_request.nil?
              @my_request.each do |r| %>
              <tr><td><%= link_to r.project[:title] ,project_url(r.project) %></td>
                <td><%= link_to r.user[:email] , "/profile/" + r.user_id.to_s %>
                </td>
                <td>
                  <%= r.mount %>
                </td>
                <td>
                  <%= link_to "Accept", "/fund_request/accept/" + r.id.to_s, class: "btn btn-success", method: :post %>
                  <%= link_to "Reject", "/fund_request/reject/" + r.id.to_s, class: "btn btn-danger", method: :post %>
                </td>

              </tr>
            <% end
               end
                %>
      </table>

      <br>

    </div>
  </div>


<% end %>

app/views/my_projects/my_foundings.erb
<%= render 'aside_menu', :selected_item=>2 do %>
  <div class="col-sm-8" style="padding:0 0 0 0 ">
    <div class="project_show_Table animated fadeIn">
      <h1 style="color: white;text-align: center;"> Founded by <%= @user.email %></h1>
      <table class="table">
        <tr><th>Project Title</th>
          <th>Owner</th>



          <th>Mount</th>
          <th>Founded at</th>

        </tr>

        <%@my_foundings_rows.each do |founding_row|
        project=founding_row.project
        %>
              <tr><td><%= link_to project[:title] ,project_url(project) %></td>
                <td><%=link_to  project.user.email, user_profile_url(project.user)%>
                </td>
                <td><%= founding_row.mount%>
                </td>
                <td><%= founding_row.created_at.to_date%>
              </td>

              </tr>
            <%

               end %>
      </table>

      <br>

    </div>
  </div>


<% end %>

app/views/my_projects/my_wishlist.erb
<%= render 'aside_menu', :selected_item=>1 do %>
  <div class="col-sm-8" style="padding:0 0 0 0 ">

    <div class="project_show_Table animated fadeIn">
      <div style="color: green"><%= flash[:wishlist] %></div>
      <h1 style="color: white;text-align: center;"> Wishlist by <%= @user.email %></h1>

      <table class="table">
        <tr><th>Project Title</th>
          <th>Owner</th>

          <th>Date</th>

          <th>Delete</th>

        </tr>

        <%wishlist=Wishlist.find_by(user_id:@user.id)

          if not wishlist.nil?
            projects= wishlist.projects
            if not projects.nil?
              @user.wishlist.projects.each do |project| %>
            <tr><td><%= link_to project[:title] ,project_url(project) %></td>
              <td><%= project.status%>
              </td>
              <td><%= project.delivery_date do%>
                  <i class="glyphicon glyphicon-edit center"></i>
                <% end %>
              </td>
              <td><%= link_to '/wishlist/project/?wishlist=' + wishlist.id.to_s + ';project=' + project.id.to_s, :method=> 'delete' do%>
                  <i class="glyphicon glyphicon-remove center"></i>
                <% end %>
              </td>

            </tr>
          <% end
          end
          end %>
      </table>

      <br>

    </div>
  </div>


<% end %>

app/views/my_projects/view_all.html.erb
<%= render 'aside_menu', :selected_item=>0 do %>
  <div class="col-sm-8" style="padding:0 0 0 0 ">
    <div class="project_show_Table animated fadeIn">
      <h1 style="color: white;text-align: center;"> Projects by <%= @user.email %></h1>

      <table class="table">
        <tr><th>Project Title</th>
          <th>Published?</th>

          <th>Edit</th>
          <th>Delete</th>

        </tr>
        <% @user.projects.each do |project| %>
          <tr><td><%= link_to project[:title] ,project_url(project) %></td>
            <td><%= project.status%>
            </td>
            <td><%= link_to edit_project_url(project) do%>
                <i class="glyphicon glyphicon-edit center"></i>
              <% end %>
            </td>
            <td><%= link_to project_url(project), :method=> 'delete' do%>
                <i class="glyphicon glyphicon-remove center"></i>
              <% end %>
            </td>

          </tr>
        <% end %>
      </table>

      <br>

    </div>
  </div>



<% end %>