config/routes.rb
Rails.application.routes.draw do
  get '/404', :to => 'application#page_not_found'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations",omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'auth/google_oauth2/callback', to: 'users/sessions#create'
  end
  get '/users/:id/edit', to: "users/registrations/#edit"
  resources :categories
  get '/my_projects', to: "my_projects#view_all", as:"my_projects"
  get '/fund_request', to: "my_projects#fund_request", as:"fund_request"
  get '/my_wishlist', to: "my_projects#my_wishlist", as:"my_wishlist"
  get '/my_foundings', to: "my_projects#my_foundings", as:"my_foundings"
  post '/create_promise', to: "my_projects#create_promise"
  post '/delete_promise', to: "my_projects#delete_promise"
  post '/create_item', to: "my_projects#create_item"

  get '/admin', to: "admin#index", as:"admin"
  resources :projects
  get '/', to: "home#index", as:'home'
  get 'login', to: "session#login"
  post 'login', to: "session#create"
  get '/profile/:id', to: "profile#show", as: "user_profile"
  get '/edit_profile/:id', to: "profile#edit"
  patch '/edit_profile', to: "profile#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/payment/promises/:id', to: "payments#promises", as: "pay_promise"
  post '/payment/pay', to: "payments#pay"

  get '/payments/fund/:id', to: "payments#fund"

  get '/admin/get_users', to: "admin#get_users", as: 'admin_get_users'
  get '/admin', to: "admin#index"

  post '/wishlist/project/', to: "my_projects#add_to_wishlist"
  delete '/wishlist/project/', to: "my_projects#remove_from_wishlist"
  post '/projects/status/:id', to: "projects#status"
  get '/projects/categories/search', to: "categories#search_by_category"

  post '/fund_request/reject/:id', to: "my_projects#reject_fund"
  post '/fund_request/accept/:id', to: "my_projects#accept_fund"


end

app/models/card_type.rb
class CardType < ApplicationRecord
  has_many :credit_cards
  validates :company, length: {minimum: 0, maximum: 10 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :project_category
  has_many :project,through: :project_category
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
  belongs_to :card_type

  validates :user, presence: true
  validates :number, numericality: {greater_than: 10}
end

app/models/founding.rb
class Founding < ApplicationRecord
  belongs_to :project
  belongs_to :user
  validates :mount, numericality: { greater_than: 0}
  before_create :create_token
  def create_token
    exist = true
    hash_value = ""
    while exist != nil
      values = "123455678890abcdefghijklmoprstuvwxyzABCDEFGHIJKLMOPQRSTUVWXYZ.+-_"
      hash_value = (0...100).map { (65 + rand(26)).chr }.join
      exist = Founding.find_by(token:hash_value)
    end
    self.token = hash_value
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :promise
  has_one :multimedia_content
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :promise , optional: true
  belongs_to :credit_card
  belongs_to :project
  before_create :create_token
  def create_token
    exist = true
    hash_value = ""
    while exist != nil
      values = "123455678890abcdefghijklmoprstuvwxyzABCDEFGHIJKLMOPQRSTUVWXYZ.+-_"
      hash_value = (0...100).map { (65 + rand(26)).chr }.join
      exist = Payment.find_by(token:hash_value)
    end
    self.token = hash_value
  end
end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :role_permissions
  has_many :roles, through: :role_permissions
  validates_format_of :name, :with => /[a-z ]+/i,:message => "can only contain letters"
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one :multimedia_content
  accepts_nested_attributes_for :multimedia_content
  validates_format_of :name, :last_name, :with => /[a-z]+/i,:message => "can only contain letters"
  validates :user, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :promises, :dependent => :delete_all
  has_many :foundings, :dependent => :delete_all
  has_many :multimedia_contents, :dependent => :delete_all
  has_many :wishlist_projects, :dependent => :delete_all
  has_many :project_category, :dependent => :delete_all
  has_many :category,through: :project_category
  accepts_nested_attributes_for :promises
  validates :goal_amount, numericality: {greater_than: 0}
  validate :date_validate


  def date_validate
    if self.delivery_date < Date.today
      return false
    end
  end

  def self.status_by_id
    return {1=>"waiting",2=>"published",3=>"rejected"}
  end

  def self.status_by_name
    return {"waiting"=>1,"published"=>2,"rejected"=>3}
  end

  def self.STATUS_WAITING
    1
  end


end

app/models/promise.rb
class Promise < ApplicationRecord
  belongs_to :project
  has_many :items
  validates :price, numericality: {greater_than: 0}
  validates :quantity, numericality: {greater_than: 0}
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user
  has_many :role_permissions
  has_many :roles, through: :role_permissions
  validates_format_of :name, :with => /[a-z ]+/i

end

app/models/role_permission.rb
class RolePermission < ApplicationRecord
  belongs_to :role
  belongs_to :permission
  validates :role_id, presence: true
  validates :permission_id, presence: true

end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  before_validation :default_role
  has_one :wishlist
  belongs_to :role
  has_one :profile
  has_many :projects
  has_many :credit_cards
  accepts_nested_attributes_for :profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]
  before_create :create_token

  def create_token
    exist = true
    hash_value = ""
    while exist != nil
      values = "123455678890abcdefghijklmoprstuvwxyzABCDEFGHIJKLMOPQRSTUVWXYZ.+-_"
      hash_value = (0...100).map { (65 + rand(26)).chr }.join
      exist = User.find_by(token:hash_value)
    end
    self.token = hash_value
  end


  def default_role
    if self.role_id == nil
      self.role_id = 1;

    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
      user.save
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.google_oauth2_data"]
        user.email = data["email"] if user.email.blank?
        user_info=data[:info]
        name=user_info[:name]
        last_name=user_info[:last_name]
        profile_params={name:name,last_name:last_name,multimedia_content_params:{}}
        user.profile_params=profile_params
      end
    end
  end

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many :wishlist_projects
  has_many :projects, through: :wishlist_projects
  validates :user_id, presence: true
end

app/helpers/admin_helper.rb
module AdminHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
  def markdown(text)
    options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" },
        space_after_headers: true,
        fenced_code_blocks: true
    }

    extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/index.html.erb
<style>
  .nav>li>a{

  }

</style>
<div style="color: white;background: rgba(0,0,0,0.6);padding: 10px 30px 10px 30px;width: 95%;margin-left: 2.5%" class="col-sm-12 animated lightSpeedIn">
  <p style="color:green"><%= flash[:notice] %></p>
<h1 id="">  Admin </h1>
<hr>

<div class="container center-block" style="margin: 0px 20px 0px 10px; padding-right: 50px">
  <ul class="nav nav-tabs">
    <li class="active"><a id="users_tab_link" data-toggle="tab"href="#users_div">Users</a></li>
    <li><a id="projects_tab_link" data-toggle="tab"href="#projects_div">Projects</a></li>
    <li><a id="categories_tab_link"data-toggle="tab"href="#categories_div">Categories</a></li>
  </ul>
  <br>
  <div class="tab-content">

    <div id="users_div" class="tab-pane fade in active">

      <table class="table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Role</th>


        </tr>
        </thead>
        <tbody id="tbody">

        </tbody>
      </table>
    </div>

    <div id="projects_div" class="tab-pane fade in">
      <table class="table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Owner</th>
          <th>Created at</th>
          <th>Status</th>
          <th>Edit</th>
          <th>Delete</th>


        </tr>
        </thead>
        <tbody id="projects_tbody">

        </tbody>
      </table>



    </div>

    <div id="categories_div" class="tab-pane fade in">
      <table class="table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Edit</th>
          <th>Delete</th>


        </tr>
        </thead>
        <tbody id="categories_tbody">

        <%@categories.each do |category|%>
        <tr>
          <td><%=category.name%></th>
          <td><%=category.description%></td>
          <td><%= link_to edit_category_url(category) do%>
              <i class="glyphicon glyphicon-edit center"></i>
            <% end %>
          </td>
          <td><%= link_to category_url(category), method: "delete" do%>
              <i class="glyphicon glyphicon-remove center"></i>
            <% end %>
          </td>
        </tr>

        <%end%>
        </tbody>
      </table>
      <%= form_tag({:controller => "categories", :action => "new"}, :method => :get)  do %>
        <div><%= submit_tag('Add Category',:class=>"btn btn-primary") %></div>
      <% end %>

    </div>






   </div>



  </div>

</div>

<script>
    $( document ).ready(function() {
        $.ajax({
            url: '/admin/get_users', success: function (result) {

                var tbody = $("#tbody")
                for (var i = 0; i < result.length; i++) {
                    var tr = document.createElement('tr')

                    var user_object = result[i]
                    var user_name;
                    if (user_object["name"]) {
                        user_name = user_object["name"]
                    }
                    else {

                        user_name = "Sin perfil definido"
                    }

                    var user_id=user_object["id"];
                    var user_email = user_object["email"]
                    var user_role = user_object["role_name"];
                    var delete_button ="";
                    tr.innerHTML += "<td>" + user_name + "</td><td><a href='/profile/"+user_id+"'>" + user_email + "</a></td><td>" + user_role + "</td>";
                    tbody.append(tr);


                }
            }
        });


        $.ajax({
            url: '/projects.json', success: function (result) {
                var tbody = $("#projects_tbody");
                for (var i = 0; i < result.length; i++) {
                    var tr = document.createElement('tr')

                    var project_jo = result[i]
                    var proj_id = project_jo["id"];
                    var project_title = project_jo["title"]
                    var project_status = project_jo["status"]
                    var project_creation = project_jo["created_at"]
                    var project_url = project_jo["url"]
                    var user_jo = project_jo["user"]
                    var user_email = user_jo["email"];
                    var delete_button ="<a href='/projects/"+proj_id+"' data-method='delete'><i class='center glyphicon glyphicon-remove'></i></a>";
                    var edit_button ="<a href='/projects/"+proj_id+"/edit'><i class='center glyphicon glyphicon-edit'></i></a>";

                    tr.innerHTML += "<td><a href='/projects/"+ proj_id +"'>" + project_title + "</a></td><td><a href='/profile/"+user_jo['id']+"'>" + user_email + "</a></td><td>" + project_creation + "</td><td>" + project_status + "</td><td>" +edit_button+ "</td><td>"+delete_button+"</td>"
                    tbody.append(tr);

                }
            }
        });

        $("#add_category").click (function () {



    });
    });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>CourseProjectStrarWithUs</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <%= stylesheet_link_tag    'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" integrity="sha384-OHBBOqpYHNsIqQy8hL1U+8OXf9hH6QRxi0+EODezv82DfnZoV7qoHAZDwMwEJvSw" crossorigin="anonymous">
    <style>
      .nav>li>a {
        position: relative;
        display: block;

        font-size: 10px;
      }
        
        


    </style>
  </head>


<header style="padding:10px 10px 10px 10px;">
<div class="nav_bar">
  <div class="nav_buttons_container">
    <a class="nav_bar_button" href="/">Start With Us</a>
    <% if current_user %>
      <% if current_user.role.name == "Admin" %>
        <a class="nav_bar_button" href="/admin">Admin</a>
      <% end %>
    <% end %>
    <a class="nav_bar_button" href="/projects">Projects</a>
    <% if user_signed_in? %>
      <a class="nav_bar_button" href="/profile/<%= current_user.id %>">Profile</a>
      <a class="nav_bar_button" href="<%= my_projects_url %>">My Projects/Wishlist</a>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav_bar_button" %>
    <% else %>
      <a class="nav_bar_button" href="/users/sign_in">Log In</a>
    <% end %>

  </div>
</div>

</header>
<body id="body_main" style="background: url(<%= asset_path 'background.jpg' %>) center center no-repeat ; background-size:  100% 100% ;overflow-x: hidden" >
<%= yield %>
</body>
<footer style="height: 50px;width: 100%;">

</footer>
<%# commented line
<footer style="position: relative">
  <div class="navbar navbar-inverse bottom" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <!-- content -->
      </div>
    </div>
  </div>
</footer></footer>

-%>


</html>
<script>
    $.fn.extend({
        animateCss: function (animationName, callback) {
            var animationEnd = (function (el) {
                var animations = {
                    animation: 'animationend',
                    OAnimation: 'oAnimationEnd',
                    MozAnimation: 'mozAnimationEnd',
                    WebkitAnimation: 'webkitAnimationEnd',
                };

                for (var t in animations) {
                    if (el.style[t] !== undefined) {
                        return animations[t];
                    }
                }
            })(document.createElement('div'));

            this.addClass('animated ' + animationName).one(animationEnd, function () {
                $(this).removeClass('animated ' + animationName);

                if (typeof callback === 'function') callback();
            });

            return this;
        },
    });

    function BodySize()
    {
        var body = $("#body_main");
        var size = body.height();
        var height = window.innerHeight;
        if (size < height)
        {
            body.css("height", height.toString() + "px")
        }
    }
    $(document).ready(function () {
        BodySize();
    });
</script>