config/routes.rb
Rails.application.routes.draw do
  get '/404', :to => 'application#page_not_found'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations",omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'auth/google_oauth2/callback', to: 'users/sessions#create'
  end
  get '/users/:id/edit', to: "users/registrations/#edit"
  resources :categories
  get '/my_projects', to: "my_projects#view_all", as:"my_projects"
  get '/fund_request', to: "my_projects#fund_request", as:"fund_request"
  get '/my_wishlist', to: "my_projects#my_wishlist", as:"my_wishlist"
  get '/my_foundings', to: "my_projects#my_foundings", as:"my_foundings"
  post '/create_promise', to: "my_projects#create_promise"
  post '/delete_promise', to: "my_projects#delete_promise"
  post '/create_item', to: "my_projects#create_item"

  get '/admin', to: "admin#index", as:"admin"
  resources :projects
  get '/', to: "home#index", as:'home'
  get 'login', to: "session#login"
  post 'login', to: "session#create"
  get '/profile/:id', to: "profile#show", as: "user_profile"
  get '/edit_profile/:id', to: "profile#edit"
  patch '/edit_profile', to: "profile#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/payment/promises/:id', to: "payments#promises", as: "pay_promise"
  post '/payment/pay', to: "payments#pay"

  get '/payments/fund/:id', to: "payments#fund"

  get '/admin/get_users', to: "admin#get_users", as: 'admin_get_users'
  get '/admin', to: "admin#index"

  post '/wishlist/project/', to: "my_projects#add_to_wishlist"
  delete '/wishlist/project/', to: "my_projects#remove_from_wishlist"
  post '/projects/status/:id', to: "projects#status"
  get '/projects/categories/search', to: "categories#search_by_category"

  post '/fund_request/reject/:id', to: "my_projects#reject_fund"
  post '/fund_request/accept/:id', to: "my_projects#accept_fund"


end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :promises, :dependent => :delete_all
  has_many :foundings, :dependent => :delete_all
  has_many :multimedia_contents, :dependent => :delete_all
  has_many :wishlist_projects, :dependent => :delete_all
  has_many :project_category, :dependent => :delete_all
  has_many :category,through: :project_category
  accepts_nested_attributes_for :promises
  validates :goal_amount, numericality: {greater_than: 0}
  validate :date_validate


  def date_validate
    if self.delivery_date < Date.today
      return false
    end
  end

  def self.status_by_id
    return {1=>"waiting",2=>"published",3=>"rejected"}
  end

  def self.status_by_name
    return {"waiting"=>1,"published"=>2,"rejected"=>3}
  end

  def self.STATUS_WAITING
    1
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new,:edit,:create,:update,:destroy]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @content = MultimediaContent.where(:project_id => @project.id).first
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create

    @project = Project.create(project_params)
    @project.update(status:"waiting")
    p = params[:project][:promise]
    if p != nil
      Promise.create(description: p[:description], quantity: p[:quantity], price: p[:price], project_id: @project.id)
    end
    categories=params[:categories]
    if categories != nil
      categories.each do |cat|
        cat=Category.find(cat)
        @project.category<<cat
      end
    end
    puts @project.category.as_json
    respond_to do |format|
      if @project.save
        content = MultimediaContent.create(project_id: @project.id, profile_id: nil, item_id: nil, image: params[:project][:multimedia_content])
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { redirect_to '/projects/new'}
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def status
    project = Project.find(params[:id])
    method = params[:method]
    if method == "delete"
      project.update(status:"rejected")
      flash[:error] = "Project was Rejected"
      project.save
      redirect_to "/projects/" + project.id.to_s
    elsif method == "accept"
      project.update(status:"published")
      project.save
      flash[:notice] = "Project was Accepted"
      redirect_to "/projects/" + project.id.to_s
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head   :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:user_id, :title, :description, :goal_amount, :status, :delivery_date,)
    end

    def image_params
      params.require(:multimedia_content).permit(:project_id, :user_id, :item_id ,:image,:category_ids)
    end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :users %>
    <%= form.text_field :users, id: :project_users %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string, id: :project_string %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string, id: :project_string %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer, id: :project_integer %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string, id: :project_string %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, id: :project_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="edit_profile_panel">
  <p style="color: green"><%= flash[:created_promise] %></p>
  <p style="color: red"><%= flash[:deleted_promise] %></p>
  <p style="color: green"><%= flash[:item_created] %></p>
  <h1 style="padding-top: 10px">Editing Project</h1>

  <%= form_for @project, method: "patch" do |pj| %>
   <div class="my_row">
    <label>Title</label>
    <%= pj.text_field :title %>
   </div>
    <div class="my_row">
  <label>Description</label>
  <%= pj.text_field :description %>
    </div>
    <div class="my_row">
  <label>Goal Amount</label>
  <%= pj.text_field :goal_amount %>
    </div>
    <div class="my_row">
      <label>Delivery Date</label>
      <div style="color:black;">
      <%= pj.date_select :delivery_date %>
      </div>
    </div>
    <% if @project.promises.size() > 0 %>
    <table>
      <tr>
        <th>Descripcion</th>
        <th colspan="2">Acciones</th>
      </tr>
      <tr>
        <% @project.promises.each do |p| %>
        <tr>
          <td><%= p.description %></td>
          <td><%= link_to "", "/delete_promise?id=" + p.id.to_s + ";project_id=" + @project.id.to_s, method: :post, class: "btn btn-danger", title: "Delete" %>
            <button id="add_item" data="<%= p.id.to_s %>" class="btn btn-primary" type="button">Add Item</button><br>

          </td>
        </tr>
        <% end %>
      </tr>
    </table>
      <br>
    <% end %>
  <%= pj.submit "Update", style:"position:relative;right:3px;bottom:3px", class: "btn btn-success" %>
  <% end %>
  <button id="add_promise" class="btn btn-primary" type="button">Add Promise</button><br>

  <%= link_to 'Show', @project %> |
  <%= link_to 'Back', projects_path %>

</div>

<!-- The Modal -->
<div id="myModal" class="modal animated fadeIn">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <%= form_tag("/create_promise") do |p| %>
      <%= hidden_field_tag :project_id, @project.id %>
      <%= label_tag("Description") %>
      <%= text_field_tag :description %><br>
      <%= label_tag("Image") %>
      <%= file_field_tag :image %><br>
      <%= label_tag("Price") %>
      <%= text_field_tag :price %><br>
      <%= label_tag("Quantity") %>
      <%= text_field_tag :quantity %><br>
      <%= submit_tag("Create!", class: "btn btn-success") %>
    <% end %>
  </div>

</div>

<!-- The Modal -->
<div id="itemModal" class="modal animated fadeIn">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <%= form_tag("/create_item", :method=> :post, multipart:true ) do |p| %>
      <%= hidden_field_tag :project_id, @project.id %>
      <%= hidden_field_tag :promise_id %>
      <%= label_tag("Name") %>
      <%= text_field_tag :name %><br>
      <%= label_tag("Image") %>
      <%= file_field_tag :image%><br>
      <%= submit_tag("Create!", class: "btn btn-success") %>
    <% end %>
  </div>

</div>
<script>
function Modal(){

    var item = document.getElementById('itemModal');

// Get the button that opens the modal
    var btn1 = $("[id^=add_ite]");

// Get the <span> element that closes the modal
    var span1 = document.getElementsByClassName("close")[0];
    span1.onclick = function() {
        modal.style.display = "none";
    }

    $(btn1).click(function() {
        var value = $(this).attr('data');
        console.log(value);
        $("#promise_id").val(value);
        item.style.display = "block";
    });
    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == item) {
            item.style.display = "none";
        }
    }

    var modal = document.getElementById('myModal');

// Get the button that opens the modal
    var btn = $("[id^=add_promis]");

// Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];
    span.onclick = function() {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
    $(btn).click(function() {
        modal.style.display = "block";
    });

}
Modal();
</script>

app/views/projects/index.html.erb
<div class="project_show_Table animated fadeInRight">
  <p style="color: red"><%= flash[:category_error] %></p>
  <%= form_tag "/projects/categories/search", method: "get" do |category| %>
    <%= label_tag "Find by Category" %><br/>
    <%= text_field_tag :category, "", style:"color:black;border-radius:12px" %>
    <%= submit_tag "Search", style: "color:black;border-radius:12px" %>
  <% end %>
<h1 style="color: white;text-align: center;">Projects</h1>
<p hidden id="notice-wishlist"></p>
<table class="table">
  <thead style="color: white;">
    <tr>
      <th width="20%">Title</th>
      <th>Description</th>
      <th width="10%">Goal Amount</th>
      <th>Status</th>
      <th>Delivery Date</th>
      <th width="10%" colspan="3"></th>
    </tr>
  </thead>

  <tbody id="project_table" style="color: white;">
    <% @projects.each_with_index do |project, index| %>
      <tr id="row_data<%= index %>">
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td>$ <%= project.goal_amount %></td>
        <td><%= project.status %></td>
        <td><%= project.delivery_date %></td>
        <td><%= link_to 'Go To Project', project, class: "btn btn-primary" %></td>
        <% if current_user %>
        <td><button title="Add to wishlist" style="background: transparent" href="#" id="addToWishlist<%= project.id %>" project-data="<%= project.id %>"> <i class="glyphicon glyphicon-plus"></i></button> </td>
        <% end %>
          </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>
</div>
<script>
function addToWishlist() {
  $("[id^=addToWishlist]").click(function () {
      $.ajax({
          url: "/wishlist/project/",
          type: "Post",
          data: {id: $(this).attr("project-data")},
          success: function(data){
              if (data["success"] == "exist"){
                  $("#notice-wishlist").text("This project is already added to your wishlist");
                  $("#notice-wishlist").show();
                  $("#notice-wishlist").css("color", "red");
                  $("#notice-wishlist").fadeOut(2000);
              }
              else if (data["success"] == true){
                  $("#notice-wishlist").text("Added to wishlist");
                  $("#notice-wishlist").show();
                  $("#notice-wishlist").css("color", "green");
                  $("#notice-wishlist").fadeOut(2000);
              }
          }
      });
  });
}


$(document).ready(function () {
   addToWishlist();
});
</script>

app/views/projects/new.html.erb
<div class="project_create_view animated zoomIn">
  <h1>New Project</h1>

  <%= form_for @project, method: "post" do |pj| %>
    <div>
      <label>Title</label>
      <%= pj.text_field :title %>
    </div>
    <div>
      <label>Description</label><br />
      <%= pj.text_area :description %>
    </div>

    <div>
      <label>Categories</label><br />



      <% Category.all.each  do |category| %>
        <input class="left" type="checkbox" style="width: 13px"id="categories[<%=category.id%>]" name="categories[<%=category.id%>]" value="true" />

        <label for="categories[<%=category.id%>]"><%=category.name%></label>

        <br />


    <% end %>
      </div>
    <div>
      <label>Goal Amount</label>
      <%= pj.text_field :goal_amount %>
    </div>

    <div>
      <label>Delivery Date</label>
      <%= pj.date_select :delivery_date %>
      <%= pj.hidden_field :user_id, :value => current_user.id %>
    </div>
    <label>Image</label>
    <%= pj.file_field :multimedia_content %>
    <br/>
    <%= pj.fields_for :promise do |promise| %>
    <table id="items_table" class="table">
      <thead>
        <tr><th>Description</th><th>Quantity</th><th>Price</th></tr>
      </thead>
      <tbody style="color: black">
    <tr class="animated fadeIn"><td><%= promise.text_field :description %></td><td><%= promise.text_field :quantity %></td><td><%= promise.text_field :price %></td></tr>
   </tbody>
    </table>
    <% end %>
    <%= pj.submit "Create", :class=> "btn btn-success" %>
  <% end %>
    <br />
  <%= link_to 'Back', projects_path, class: "btn btn-danger" %>
</div>

app/views/projects/show.html.erb
<div class="project_view animated zoomIn">
  <% if current_user != nil %>
    <% if current_user.role.name == "Admin" %>
      <div class="my_row">
        <p>
        <p style="color: green;" id="notice"><%= notice %></p>
        <p style="color: red;"><%= flash[:error] %></p>
        <h2 style="text-transform: uppercase"><%= @project.status %></h2>
         <%= link_to '/projects/status/' +@project.id.to_s+'?method=accept' , method:"post", class:"btn btn-success", style:"border-radius: 12px", title:"Accept" do %>
          <i class="glyphicon glyphicon-plus"></i>
         <% end %>
        <%= link_to '/projects/status/' +@project.id.to_s+'?method=delete', method:"post",class:"btn btn-danger", style:"border-radius: 12px", title:"Reject" do %>
          <i class="glyphicon glyphicon-remove"></i>
        <% end %>
        </p>
      </div>
    <% end %>
  <% end %>
  <% if @project.user == current_user %>
    <div class="my_row">
      <%= link_to "Edit!", "/projects/" + @project.id.to_s + "/edit", class: "btn btn-primary" %>
    </div>
    <% end %>

  <div class="my_row">
    <p>
    <h2><%= @project.title %></h2>

    </p>
  </div>
  <% if @content %>
    <div class="my_row">
      <p>
        <strong>Image:</strong>
        <img style="height: 300px;width: 300px;margin-left: 25px;  %" src="<%= @content.image %>">
      </p>
    </div>
  <% end %>
  <div class="my_row">
    <p>
      <strong style="text-align: center">Project Owner</strong> <br/>
      <%= link_to @project.user[:email], '/profile/' + @project.user_id.to_s %>
    </p>
  </div>
  <div class="my_row">
    <p>
      <strong>Description:</strong>
    <div><%= @project.description %></div>
    </p>
  </div>
  <div class="my_row">
    <p>
      <strong>Goal Amount: $</strong>
      <%= @project.goal_amount %>
    </p>
  </div>


  <div class="my_row">
    <p>
      <strong>Delivery Date: </strong>
      <%= @project.delivery_date %>
    </p>
  </div>
  <% if current_user != nil %>
  <input id="addToWishlist" type="button" project-data="<%= @project.id %>" class="btn btn-primary" value="Add to wishlist" style="margin-top: 10px">

    <%end%>
    </div>
<button id="prev_promise" class="promises-manage-button-left animated zoomIn">
  <img src="<%= image_url("left_arrow.png") %>"></button>
<button id="next_promise" class="promises-manage-button-right animated zoomIn">
  <img src="<%= image_url("left_arrow.png") %>"></button>
<div class="promises_view animated zoomIn">
  <div class="my_row">
    <strong id="head_promises">Promises 1/<%= @project.promises.count %></strong>
  </div>
  <% counter = 0 %>
  <% @project.promises.each do |promise| %>

   <% if counter == 0 %>
    <div id="promise0" class="my_row_promises">
   <% else %>
      <div id="promise<%= counter.to_s %>" class="my_row_promises" hidden>
   <% end %>
      <div style="width: 15%;margin-top: 5px;position: relative;float: right;margin-right: -6%">Price:
        <%= promise.price %>
      </div>
      <div style="width: 15%;margin-top: 25px;position: relative;float: right;margin-right: -12%">Quantity:
        <%= promise.quantity %>
      </div>
      <% value = 0 %>

    <button class="my_right_button" id ="item_slider_button_right<%= counter.to_s %>" >
      <i class="glyphicon glyphicon-chevron-right"></i></button>

      <% promise.items.each do |item| %>

      <% if value == 0 %>
        <div id="item<%= counter.to_s + value.to_s %>" style="overflow: hidden;width: 200px;height: 160px;float:right;">
        <% else %>
        <div id="item<%= counter.to_s + value.to_s %>" style="overflow: hidden;width: 200px;height: 160px;float:right;" hidden>
        <% end %>
        <% value += 1 %>
        <img style="height: 140px;width: 80px;position: absolute" src="<%= item.multimedia_content.image %>">
        <span style="position: absolute;margin-left: 90px;">Item: <%= item.name %></span><br/>
        <span style="position: absolute;margin-left: 90px;width: 130px">Description:<br/> <%= item.description %></span>
        </div>
      <% end %>
    <button class="my_left_button" id ="item_slider_button_left<%= counter.to_s %>">
      <i class="glyphicon glyphicon-chevron-left"></i></button>
    <p hidden id="item-len-<%= counter.to_s %>"><%= value.to_s %></p>
      <div style="width: 50%;position: relative;margin-top: 0px;height: 100%">
        <%= promise.description %>
      </div>
    <% if current_user %>
    <%= link_to "Buy", '/payment/promises/' + promise.id.to_s, class: "btn btn-success", style: "float: left;margin-top: -50px;" %>
    <% end %>
      </div>
    <% counter += 1 %>
  <% end %>

  <p hidden id="promises-len"><%= counter.to_s %></p>
  <% if current_user %>
  <%= link_to 'Fund Project', '/payments/fund/' + @project.id.to_s, class: "btn btn-primary" %>
  <% end %>
  <%= link_to 'Back', projects_path, class: "btn btn-danger" %>
  </div>
  <script>
var actual_promise = 0;
var actual_item = 0;

var head_actual_promise = $("#head_promises").text().split(" ")[1].split("/");
var len_promises = head_actual_promise[1];
var len_actual_promises_items = 0;

function ItemsManage() {
$("[id^=item_slider_button_left]").click(function () {
    if (actual_item > 0) {
        var next = "item" + actual_promise.toString() + (actual_item - 1).toString();
        var actual_id = "item" + actual_promise.toString() + (actual_item).toString();
        var actual_obj = $("#" + actual_id);
        var next_obj = $("#" + next);
        actual_obj.attr("class", "");
        next_obj.attr("class", "");
        actual_obj.animateCss("fadeOutRight",function () {
           actual_obj.hide() ;
            next_obj.show();
            next_obj.animateCss("fadeInLeft");
        });

        actual_item -= 1;


    }
});
$("[id^=item_slider_button_right]").click(function () {
    if (actual_item < 1) {
        var next = "item" + actual_promise.toString() + (actual_item + 1).toString();
        var actual_id = "item" + actual_promise.toString() + (actual_item).toString();
        var actual_obj = $("#" + actual_id);
        var next_obj = $("#" + next);
        actual_obj.attr("class", "");
        next_obj.attr("class", "");
        actual_obj.animateCss("fadeOutLeft",function () {
            actual_obj.hide();
            next_obj.show();
            next_obj.animateCss("fadeInRight");
        });
        actual_item += 1;
    }
  });
}


function addToWishlist() {
    $("#addToWishlist").click(function () {
        $.ajax({
            url: "/wishlist/project/",
            type: "Post",
            data: {id: $(this).attr("project-data")},
            success: function(data){
                var flash=data["flash"]
                $("#notice").html("<%= flash[:notice] %>");
                alert(flash)
                console.log(flash);
            }
        });
    });
}


function PromisesManage() {
    var promises_len = $("#promises-len").text();
    $("#next_promise").click(function () {
        if (actual_promise < promises_len - 1) {
            var actual_promise_obj = $("#promise" + actual_promise.toString());
            var next_promise = $("#promise" + (actual_promise + 1).toString());
            actual_promise_obj.attr("class", "my_row_promises");
            next_promise.attr("class", "my_row_promises");
            actual_promise_obj.hide();
            next_promise.show();
            next_promise.addClass("animated flipInX");
            actual_promise += 1;
            actual_item = 0;
            $("#head_promises").text("Promises " + (actual_promise + 1).toString() + "/" + len_promises);
        }
    });
    $("#prev_promise").click(function () {
        if (actual_promise > 0) {
            var actual_promise_obj = $("#promise" + actual_promise.toString());
            var next_promise = $("#promise" + (actual_promise - 1).toString());
            actual_promise_obj.attr("class", "my_row_promises");
            next_promise.attr("class", "my_row_promises");
            next_promise.show();
            actual_promise_obj.hide();
            next_promise.addClass("animated flipInX");
            actual_promise -= 1;
            actual_item = 0;
            $("#head_promises").text("Promises " + (actual_promise + 1).toString() + "/" + len_promises);
        }
    });
}
$(document).ready(function () {

    PromisesManage();
    ItemsManage();
    addToWishlist();
});

  </script>
  </div>

</div>